### ISSUE TITLE
mongoDB StorageAdapter returns wrong JSON

### ISSUE THREAD

**Issue by Manu3756** [SAP/i40-aas#47]
The mongoDB-stroage-adapter returns 

`[
{
"_id": "c2acfc0146ac0a6e5f52b5c62aac02b7",
"version": 1,
"serializedState": "{\"qualifiers\":[],\"idShort\":\"opc-ua-devices\",\"modelType\"

:.........

[],\"idShort\":\"softwarerevision\",\"value\":\"\",\"valueType\":{\"dataObjectType\":{\"name\":\"string\"}}}]}"
}
]`

it should return only the content of serializedState property. 

**steps to reproduce:**

* docker-compose up

* register mongoDB-stroage-adapter

* post sample onboarding msg 

* request /submodels?idShort=opc-ua-devices from dataManager

**Comment by kasimrehman** [comment]
The storage adapter could return only the submodel that was sent to it during creation. In that case, the receiver would not be able to get the meta-information, version, but more important, the generated (hashed id) required to operate the DELETE later. The API for the storage adapter as the storage adapter itself was only provided for testing purposes and was not meant to be for productive use or a full implementation of the AAS API. The ability to look into the database and to delete from it is vital in that case.

There are multiple possible solutions. One would be to hide the current functionality behind different endpoints. Another would be assign a field in the AAS-JSON for the generated id, which can then later be used to delete from the database. Just changing the current endpoint behaviour without one of these workarounds will result in loss of utility.

Should you decide to go for the first option, the current get endpoint would need to be implemented by: 

  async getSubmodels(): Promise<Submodel[]> {
    await this.dbClient.connect();
    return (await this.dbClient.getAll())
      .filter(x => x.serializedSubmodel)
      .map(x => JSON.parse(x.serializedSubmodel));
  }

which is a two-line change (I have not tested it). The current getSubmodels() would then e called by some admin endpoint.

**Comment by Manu3756** [comment]
The goal should be to have a running storage-adapter with a minimum set of the AAS-API 
GET /submodels
PUT /submodels 
DELETE /submodels?id=<Submodel.identification.id> 

If there are specific endpoints needed they should be marked somehow. 
I will create a PR for the first option.

**Comment by kasimrehman** [comment]
Hi Manuel,

Thank you very much for this suggestion. I do not quite like the DELETE specification. The natural candidate for an id is a path parameter, not a query parameter. This has following reasons:

1. All or at least the vast majority of implementations we see from others have id as a path parameter, so making it a query parameter will surprise most of our users. Especially, if they need to deal with a list of one (queries return lists) rather than a single element which they most likely expect when using a unique id to retrieve data.

2. We would then need to support query parameters, which are less explicit (regarding how to use them) and have more variability (and hence complexity). For example, a user might try other properties in the query.

3. The URI RFC (3986) recommends the path for hierarchical data and the query for non-hierarchical data. We have a clear hierarchy in our data: The collection of submodels contains multiple submodels. Each of those has a unique id and all its properties are to be seen in the context of (and only in the context of) that one submodel signified by that unique id. 

Does the AAS-specification specify that ids be in query parameters? What about GET?

PS:  https://medium.com/@fullsour/when-should-you-use-path-variable-and-query-parameter-a346790e8a6d also has good insights into this issue.

**Comment by Manu3756** [comment]
Hi, 
There will be an API for an AAS we need to follow what ever they specify.
So we may should wait for the spec before we implement sth.

**Comment by kasimrehman** [comment]
We will do this properly when the 2.0 spec is clear.
